// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    title: {
      type: String,
    },
    firstName: {
      type: String,
    },
    lastName: {
      type: String,
    },
    isHideName: {
      type: String,
    },
    phoneNumber: {
      type: String,
    },
    email: {
      type: String,
    },
    isCall: {
      type: Boolean,
    },
    isText: {
      type: Boolean,
    },
    isEmail: {
      type: Boolean,
    },
    category: {
      type: String,
    },
    subcategory: {
      type: String,
    },
    quantity: {
      type: Number,
    },
    fileUrl: {
      type: [String],
    },
    postTitle: {
      type: String,
    },
    postDescription: {
      type: String,
    },
    views: {
      type: Number,
      default: 0,
    },
    viewerDetails: {
      type: [String],
    },
    status: {
      type: String,
      default: 'Active',
    },
    user_id: {
      type: String,
    },
    zip_code: {
      type: String,
    },
    city: {
      type: String,
    },
    state: {
      type: String,
    },
    country: {
      type: String,
    },
  },
  { timestamps: true }
  );

  return mongoose.model('gmaches', schema, 'gmaches');
};
