// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    formType: {
      type: String,
    },
    category: {
      type: String,
    },
    subcategory: {
      type: String,
    },
    authorName: {
      type: String,
    },
    zipCode: {
      type: Number,
    },
    postTitle: {
      type: String,
    },
    flyer: {
      isSelected: Boolean,
      fileUrl: String,
      imageUrl: String,
    },
    content: {
      isSelected: Boolean,
      imageUrl: [String],
      postRemainingContent: String,
    },
    userid: {
      type: String,
    },
    views: {
      type: Number,
      default: 0,
    },
    viewerDetails: {
      type: [String],
    },
    status: {
      type: String,
      default: 'active',
    },
  },
  { timestamps: true });

  return mongoose.model('inspirationalstories', schema, 'inspirationalstories');
};
